return
        {
            "Divine Guardian Raid",
            "Blue Devil Raid",
            "Psycho Student Raid",
            "Buff Boy Raid",
            "Warlord Raid",
            "King of Curses Raid",
            "Black Pasta Raid",
            "Cosmic Wolfman Raid",
            "Joto Raid",
            "Matsuri Raid",
            "Tonjuro Sun God Raid",
            "Vio Raid",
            "Demon Lord Raid",
            "Ichini Fullbring Raid",
            "Roku Ultra Instinct Raid",
            "Chainsaw Raid",
            "Nardo Beast Raid",
            "Cursed Sage Raid",
            "Red Emperor Raid",
            "Tengu Raid",
            "Yomichi Raid",
            "Christmas Raid",
            "Infinity Nojo Raid",
            "Combat Titan Raid",
            "Esper Raid",
            "Gear 5 Fluffy Raid",
            "Tengoku Raid",
            "Hirito Raid",
            "Titan Raid"
        }
